$ANSIBLE_VAULT;1.1;AES256
39346665336332616661636239656232323763303165653531633466396135373332363038653731
6436393430666665393666313737376163336361333234610a383765323162656532613134323165
36396439303733313562623132386332336231346533633830393165396532346166643632633930
3261363865383238620a326635343166333139323230373137653466386538656532386131366431
63386239393530366538613439306335666161663136333161343365663664633735323166303364
62616436623238646664336139363662396538616566306236316566616566303832636463316230
37396633386233626136396630306139356635326266333139653264386436633662346139643938
33366135353862306565363437666139323063363033386332666166306461383963636361373262
39663134376638663833396164393365326336326131623366653430376132613366323963663665
62373362663334373735303331313863373033383539393966336566343661313135373164663036
37343862376432316666623833643639613430356662626435613365323262343033303438653630
39663933373264353135383636653662623761656330396430616639393639623434623763306633
66663030323435616537616437643434313964366264356432333564646666616264323963363038
30626536353036386465343131613038393461383132386538386534383233616136616435326339
36653032323730316237306431313366656530633464356163333030386461666164626166313064
36633965303730626163303730376535303636376133343336363336623834366130643439346431
36653766383865633365343235643563663061613737313433386336326135653563393030363462
6634323939613939333030313530313264623033326430653439
